name: iOS starter workflow

on:
  pull_request:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get status
        run: |
          response=$(curl -v -w '%{http_code}' -H "Authorization: token ${{ secrets.PAT }}" \
          https://api.github.com/repos/yasmins24/PickMyMeals/actions/workflows/build.yml/runs?per_page=1 | jq -r '.workflow_runs[0].conclusion')
          echo response
      # status=$(jq -r '.status' response)
      # conclusion=$(jq -r '.conclusion' response))
      # echo $status $conclusion
          
      # | jq -r '.workflow_runs')
      # echo $response
      # - name: Trigger build
      #   run: |
      #    curl -L \
      #    -X POST \
      #    -H "Accept: application/vnd.github+json" \
      #    -H "Authorization: Bearer ${{ secrets.PAT }}" \
      #    -H "X-GitHub-Api-Version: 2022-11-28" \
      #    https://api.github.com/repos/yasmins24/PickMyMeals/dispatches \
      #    -d '{"event_type":"run-tests"}'
      # - name: Build
      #   run: 
      #     xcodebuild -project "RecipEZ.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 15 Pro Max"
