name: iOS starter workflow

on:
  pull_request:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: 
          xcodebuild -project "RecipEZ.xcodeproj" -scheme "RecipEZ" -destination "platform=iOS Simulator,name=iPhone 15 Pro Max"
