name: iOS starter workflow

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get status for pick my meals build
        id: pickmymeals_status
        run: |
          response=$(curl -H "Authorization: token ${{ secrets.PAT }}" \
          https://api.github.com/repos/yasmins24/PickMyMeals/actions/workflows/build.yml/runs?per_page=1 | jq -r '.workflow_runs[0]')
          echo status=$(jq -r '.status' response) >> "$GITHUB_OUTPUT"
          echo conclusion=$(jq -r '.conclusion' response)) >> "$GITHUB_OUTPUT"
          echo $status $conclusion

      - name: Check statuses of all repos
        if: ${{ steps.pickmymeals_status.outputs.conclusion != 'success' }} # Replace with your desired condition
        uses: actions/github-script@v7
        with:
          script: |
            echo "Pick my meals: Run was not successful."
            exit 1

  failure:
    name: handle failure
    needs: build
    if: failure()
    runs-on: macos-latest

    steps:
      - name: Failure
        run: echo failure example

  success:
    name: handle success
    needs: build
    if: success()
    runs-on: macos-latest

    steps:
      - name: Success
        run: echo success example

          
      # | jq -r '.workflow_runs')
      # echo $response
      # - name: Trigger build
      #   run: |
      #    curl -L \
      #    -X POST \
      #    -H "Accept: application/vnd.github+json" \
      #    -H "Authorization: Bearer ${{ secrets.PAT }}" \
      #    -H "X-GitHub-Api-Version: 2022-11-28" \
      #    https://api.github.com/repos/yasmins24/PickMyMeals/dispatches \
      #    -d '{"event_type":"run-tests"}'
      # - name: Build
      #   run: 
      #     xcodebuild -project "RecipEZ.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 15 Pro Max"
