name: iOS starter workflow

on:
  pull_request:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Info
        run: echo github. 
      - name: Trigger build
        run: |
         curl -L \
         -X POST \
         -H "Accept: application/vnd.github+json" \
         -H "Authorization: Bearer ${{ secrets.PAT }}" \
         -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/yasmins24/PickMyMeals/dispatches \
         -d '{"event_type":"run-tests","client_payload": null}'
      - name: Build
        run: 
          xcodebuild -project "RecipEZ.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 15 Pro Max"
