name: iOS starter workflow

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get status for pick my meals build
        shell: bash
        id: pickmymeals_status
        run: |
           set -euo pipefail
           ./bin/check_workflow_status.sh ${{ secrets.PAT }} "PickMyMeal"
           echo Exits with a status code of $?

      - name: Check statuses of all repos
        if: steps.pickmymeals_status.outputs.PickMyMeals-conclusion == 'success'
        run: |
            echo "Pick my meals: Run completed with a status of: ${{ steps.pickmymeals_status.outputs.PickMyMeals-conclusion }}."

  failure:
    name: handle failure
    needs: build
    if: failure()
    runs-on: macos-latest

    steps:
      - name: Failure
        run: echo failure example

  success:
    name: handle success
    needs: build
    if: success()
    runs-on: macos-latest

    steps:
      - name: Success
        run: echo success example

          
      # | jq -r '.workflow_runs')
      # echo $response
      # - name: Trigger build
      #   run: |
      #    curl -L \
      #    -X POST \
      #    -H "Accept: application/vnd.github+json" \
      #    -H "Authorization: Bearer ${{ secrets.PAT }}" \
      #    -H "X-GitHub-Api-Version: 2022-11-28" \
      #    https://api.github.com/repos/yasmins24/PickMyMeals/dispatches \
      #    -d '{"event_type":"run-tests"}'
      # - name: Build
      #   run: 
      #     xcodebuild -project "RecipEZ.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 15 Pro Max"
